name: Release process

on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  release-tag:
    if: contains(github.ref, 'refs/tags/master') && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "- All the changes can be found in the [changelog](https://github.com/SamoKopecky/ssltest/blob/master/CHANGELOG.md) file"
  build-n-publish:
    if: contains(github.ref, 'refs/tags/master') && contains(github.ref, 'refs/tags/')
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --outdir dist/
          .
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
